install/uninstall fixes

diff --git a/uninstallworld b/uninstallworld
--- a/uninstallworld
+++ b/uninstallworld
@@ -8,6 +8,39 @@ QUADSTOR_ROOT="$buildroot"
 os=`uname`
 if [ "$os" = "FreeBSD" ]; then
 	sudo rm -f /boot/kernel/ispmod.ko
+	cmod=`/sbin/kldstat | grep vtlcore`
+	if [ "$cmod" != "" -a -f /etc/rc.d/quadstorvtl ]; then
+		/etc/rc.d/quadstorvtl stop > /dev/null 2>&1
+	fi
+
+	cmod=`/sbin/kldstat | grep vtlcore`
+	if [ "$cmod" != "" -a -f /etc/rc.d/quadstorvtl ]; then
+		/etc/rc.d/quadstorvtl onestop > /dev/null 2>&1
+	fi
+
+	cmod=`/sbin/kldstat | grep vtlcore`
+	if [ "$cmod" != "" ]; then
+		echo "Unable to shutdown QUADStor service cleanly. Please restart the system and try again"
+		exit 1
+	fi
+
+	cmod=`/sbin/kldstat | grep coredev`
+	if [ "$cmod" != "" ]; then
+		/etc/rc.d/quadstor stop > /dev/null 2>&1
+	fi
+
+
+	cmod=`/sbin/kldstat | grep coredev`
+	if [ "$cmod" != "" ]; then
+		/etc/rc.d/quadstor onestop > /dev/null 2>&1
+	fi
+
+	cmod=`/sbin/kldstat | grep coredev`
+	if [ "$cmod" != "" ]; then
+		echo "Unable to shutdown QUADStor service cleanly. Please restart the system and try again"
+		exit 1
+	fi
+
 	rm -f /etc/rc.d/quadstor
 else
 	if [ -d /etc/rc.d/init.d ]; then
