Stop quadstor vtl service prior to uninstall of quadstor virt

diff --git a/build/debian-core-prerm b/build/debian-core-prerm
--- a/build/debian-core-prerm
+++ b/build/debian-core-prerm
@@ -8,6 +8,17 @@ rm -f /etc/rc4.d/*quadstor
 rm -f /etc/rc5.d/*quadstor
 rm -f /etc/rc6.d/*quadstor
 
+cmod=`/sbin/lsmod | grep vtlcore`
+if [ "$cmod" != "" -a -f /etc/init.d/quadstorvtl ]; then
+	/etc/init.d/quadstorvtl stop
+fi
+
+cmod=`/sbin/lsmod | grep vtlcore`
+if [ "$cmod" != "" ]; then
+	echo "Unable to shutdown QUADStor VTL service cleanly. Please restart the system and try again"
+	exit 1
+fi
+
 cmod=`lsmod | grep coredev`
 if [ "$cmod" != "" ]; then
 	/etc/init.d/quadstor stop
